site_name: fromthehard 
site_url: https://docs.fromthehard.org/
nav:
  - Home: index.md
  - Embedded C: embedded-c.md
theme:
  name: material
  favicon: favicon.svg
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.path
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: lime
  palette:
    - media: "(prefers-color-scheme)"
      accent: lime
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: lime
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: lime
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
